version: "3.9"

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Application
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql